# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 002eaa43b74bd753ab844cce1451bc8010bc8c40428bd482f34fc46fb795a582cf6b6a92ddbd1145f5d7e3e2c059fbbe5afa973f42bf793a0b84664efea7af62

test:
  secret_key_base: 25fad1e66c869e2357ab5dd01f174e51a4e4b867060957b7d9b4c76d872d13f0565e97643c802085f2f7f560810ccb184d6d696d222c3d49ea48a0f173e530b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
